# fly.toml app configuration file generated for actual-nameless-forest-4991 on 2024-07-23T20:32:53-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'actual-nameless-forest-4991'
primary_region = 'gdl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  size = 'shared-cpu-1x'
