name: Build and Deploy Dev

on:
  push:
    branches:
      - dev
    paths:
      - 'packages/**'
      - 'package.json'
      - 'fly.toml'
      - '.github/workflows/deploy-dev.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Dev
        run: flyctl deploy --remote-only --image eduarbo/actual-server:${{ github.ref_name }}-${{ github.sha }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
